FROM node:12.14.1-alpine

WORKDIR /srv/app

# Install node modules (allows for npm install to be cached until package.json changes)
COPY package.json tsconfig.json .npmrc .yarnrc ./

# Copy our source files to the service location
COPY . .

RUN yarn install

# Set default environment variables
ENV \
	NODE_PATH=/node_modules\
	PATH=/srv/app:/node_modules/.bin:/bin:$PATH\
	PAGES_WORKER=true\
	PORT=80

RUN yarn build

# Start the server
CMD ["yarn", "start:worker"]
